# Generated by Django 4.2.3 on 2023-08-14 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_user_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.contacts')),
            ],
        ),
    ]
