# Generated by Django 4.2.3 on 2023-08-14 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_user_contacts_user_contact_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_list',
        ),
        migrations.AddField(
            model_name='user',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.contacts'),
        ),
        migrations.DeleteModel(
            name='Contact_list',
        ),
    ]
