# Generated by Django 4.2.3 on 2023-08-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_contacts_user_alter_contacts_avatar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='user',
        ),
    ]
