# Generated by Django 4.2.3 on 2023-08-15 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_contacts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
