# Generated by Django 4.2.3 on 2023-08-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_contacts_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='favourites',
            field=models.BooleanField(default=False),
        ),
    ]
