# Generated by Django 4.2.3 on 2023-08-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_contacts_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='avatar',
            field=models.ImageField(default='/static/images/default.png', null=True, upload_to=''),
        ),
    ]
