# Generated by Django 4.2.3 on 2023-08-27 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_contacts_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='last_name',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
