# Generated by Django 4.2.3 on 2023-08-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_contacts_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='Emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='avatar',
            field=models.ImageField(default='default.png', null=True, upload_to=''),
        ),
    ]
